- position: 0
  lettermap: A
  description: Front-Right-Bottom
  designation: (S0)
  high_us: 1936
  low_us: 592
  high_pos: high
  high_angle: 180.0
  low_angle: 0.0
  home_angle: 90.0
- position: 1
  lettermap: B
  description: Front-Right-Middle
  designation: S1
  high_us: 1936
  low_us: 672
  high_pos: high
  high_angle: 180.0
  low_angle: 20.0
  home_angle: 120.0
- position: 2
  lettermap: C
  description: Front-Right-Top
  designation: S2
  high_us: 1760
  low_us: 896
  high_pos: low
  high_angle: 0.0
  low_angle: 42.05
  home_angle: 100.0
